#!/usr/bin/env python3
"""Reproduce the small synthetic telemetry fixture without a MAVLink library.

This is a fixture encoder for HEARTBEAT and ATTITUDE, not a general MAVLink
implementation. The expected-observation manifest is maintained separately.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path

FIXTURE_PATH = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "telemetry-gap.tlog"
EPOCH_US = 1_700_000_000_000_000

# The literal golden vector is independently checked in the importer tests.
# MAVLink 1 HEARTBEAT: sequence=0, source=(1,1), custom_mode=0, type=2,
# autopilot=0, base_mode=0, system_status=4, mavlink_version=3; CRC=0x091c.
GOLDEN_HEARTBEAT_FRAME = bytes.fromhex("fe09000101000000000002000004031c09")


def _crc_mcrf4xx(data: bytes) -> int:
    """CRC-16/MCRF4XX: reflected 0x1021, initial 0xffff, no final XOR."""
    crc = 0xFFFF
    for value in data:
        crc ^= value
        for _ in range(8):
            crc = (crc >> 1) ^ (0x8408 if crc & 1 else 0)
    return crc


def _heartbeat() -> bytes:
    # Wire field order and CRC_EXTRA=50: minimal/mavlink_msg_heartbeat.h.
    return struct.pack("<IBBBBB", 0, 2, 0, 0, 4, 3)


def _attitude(boot_ms: int, roll: float, pitch: float, yaw: float) -> bytes:
    # Wire field order and CRC_EXTRA=39: common/mavlink_msg_attitude.h.
    return struct.pack("<Iffffff", boot_ms, roll, pitch, yaw, 0.0, 0.0, 0.0)


def _frame(
    version: int,
    system_id: int,
    sequence: int,
    message_id: int,
    crc_extra: int,
    payload: bytes,
) -> bytes:
    if version == 1:
        magic = b"\xfe"
        header = bytes((len(payload), sequence, system_id, 1, message_id))
    else:
        # MAVLink 2 removes trailing zero payload bytes, retaining at least one.
        payload = payload.rstrip(b"\x00") or b"\x00"
        magic = b"\xfd"
        header = bytes((len(payload), 0, 0, sequence, system_id, 1))
        header += message_id.to_bytes(3, "little")
    checksum = _crc_mcrf4xx(header + payload + bytes((crc_extra,)))
    return magic + header + payload + struct.pack("<H", checksum)


def build_fixture() -> bytes:
    """Return the same 12-record recording on every invocation."""
    # Each tuple is: seconds after artificial epoch, wire version, source system,
    # sequence, message ID, CRC_EXTRA, payload. Both components are component 1.
    # Boot clocks are deliberately distinct and are not capture-clock mappings.
    records = (
        (0, 1, 1, 0, 0, 50, _heartbeat()),
        (0, 2, 2, 0, 0, 50, _heartbeat()),
        (1, 2, 1, 1, 30, 39, _attitude(1000, 0.25, -0.5, 1.0)),
        (1, 1, 2, 1, 30, 39, _attitude(11000, 0.5, 0.25, -1.0)),
        (2, 2, 2, 2, 30, 39, _attitude(12000, 0.5, 0.25, -1.0)),
        (3, 1, 2, 3, 0, 50, _heartbeat()),
        (3, 2, 2, 4, 30, 39, _attitude(13000, 0.5, 0.25, -1.0)),
        (4, 1, 2, 5, 30, 39, _attitude(14000, 0.5, 0.25, -1.0)),
        (5, 1, 1, 2, 30, 39, _attitude(5000, 0.25, -0.5, 1.0)),
        (5, 2, 2, 6, 30, 39, _attitude(15000, 0.5, 0.25, -1.0)),
        (6, 2, 1, 3, 0, 50, _heartbeat()),
        (6, 1, 2, 7, 0, 50, _heartbeat()),
    )
    output = bytearray()
    for index, (seconds, version, system_id, sequence, msgid, crc, payload) in enumerate(records):
        frame = _frame(version, system_id, sequence, msgid, crc, payload)
        if index == 0 and frame != GOLDEN_HEARTBEAT_FRAME:
            raise RuntimeError("Encoder no longer reproduces the golden HEARTBEAT frame")
        output.extend(struct.pack(">Q", EPOCH_US + seconds * 1_000_000))
        output.extend(frame)
    return bytes(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with the stored fixture without writing files",
    )
    args = parser.parse_args()
    generated = build_fixture()
    if args.check:
        if not FIXTURE_PATH.is_file() or FIXTURE_PATH.read_bytes() != generated:
            print("Fixture is missing or differs from the deterministic encoder.")
            return 1
        action = "Verified"
    else:
        FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE_PATH.write_bytes(generated)
        action = "Wrote"
    print(
        f"{action} {FIXTURE_PATH.name}: {len(generated)} bytes, "
        f"SHA-256 {hashlib.sha256(generated).hexdigest()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
